[package]
name = "vivec"
version = "0.1.0"
edition = "2024"

[dependencies]
[lints.clippy]
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
unwrap-used = "warn"
missing-errors-doc = "warn"

[features]
default = [  ]
reverse_id_search = []
